### PR TITLE
C# mapping file separated from the app

### PR DESCRIPTION
**Pull request by warpech**
:construction: **work in progress**

As part of the blending discussion (https://github.com/Starcounter/RebelsLounge/issues/154 step 2), I have tried to separate the calls to `Blender.MapUri` from the app code. 

## The good 

Starcounter supports loading uncompiled single file C#.

Run it using `star Images_Map.cs`

## The bad

It requires starting the map C# file manually after starting the app actual app. 

## The ugly

Unfortunately, the proposal in this PR currently doesn't work. That is because the syntax `Blender.MapUri<T>` requires the reference to the type. In case of this app, the type comes from Simplified DLL.

Any proposals how to solve that?

We could either:

1. Use the fully qualified name of the type as a string.
2. Turn the mapping file into a compiled project instead of a single file.

I am leaning towards 1.

## Big question

Would we be comfortable in applying this in all our prefab apps and asking our customers to do the same?

cc @StarcounterApps/starcounter , @alemoi

### CODE REVIEW

**Comment by habib535** [comment]
I haven't tried it but here is the possible solution for loading blending points from outside.

1. Replace the `Main` method inside Images_Map.cs file with a different method name e.g. `MapBlendingPoints`

2. Program.cs Main method needs to accept an argument, which will be the path of Images_Map.cs file

3. using `CSharpCodeProvider ` we can load a file/string and execute it within the same process which will fix the missing reference errors.

4. In run.bat provide file path to Images.exe as an argument

**Comment by warpech** [comment]
@habib535 this suggestion will make `Images_Map.cs` part of the `Images.exe` binary, won't it? The point of this PR is to keep it outside of that binary, yet still load it to the database.

@habib535 could you pls help me out with this? I suppose that if you implement the suggestion 1 listed above, this will work.

**Comment by tomalec** [comment]
:+1: for 
> 1. Use the fully qualified name of the type as a string.

**Comment by warpech** [comment]
Thanks @habib535! I can confirm that it works. 

Now we need to respond to the big question - are we comfortable switching to it in all apps.

@alemoi, @mmnosek, @tomalec?

**Comment by alemoi** [comment]
I was worrying that `Images_Map.cs` would run as a separate app outside of context of the `Images` app. But maybe I'm wrong with it (maybe we already handler `_map` appname prefix somehow).

**Comment by warpech** [comment]
As far as I know, it does run as a totally separate app. There is no penalty in that, is it?

@per-samuelsson any opinion on merging this PR and using this pattern?

Do we have something better that can be used in 2.3.x?

**Comment by warpech** [comment]
Ping @alemoi, @per-samuelsson

**Comment by alemoi** [comment]
After the meeting with @per-samuelsson quite a while ago, we decided that the best solution is to run needed .map.cs files as apps manually (as normal apps, using `star` tool), or include them in playlists, when they are implemented. Also since we will move towards textual files (markdowns) the suggestion above by @warpech is correct: `Use the fully qualified name of the type as a string.`
Technically separate blending apps are now working, so Im closing the issue.

**Comment by warpech** [comment]
I don't understand, if this is correct then why was it closed?

**Comment by alemoi** [comment]
> I don't understand, if this is correct then why was it closed?

Already now the mapping apps can be separated, meaning its working. Regarding the autostart - its a different issue related to playlists in general.

> It requires starting the map C# file manually after starting the app actual app.

Playlists need to be implemented.

> Use the fully qualified name of the type as a string.

Exactly.

@warpech what questions you are thinking of that are not answered here?

**Comment by alemoi** [comment]
I think this issue is a bit outdated. We decided that Blending should be declarative and not contain code. There is a working solution already with `blend.json` startup file: https://github.com/Starcounter/RebelsLounge/issues/154#issuecomment-348373966
Documented here: https://docs.starcounter.io/guides/blendable-web-apps/view-attaching#separate-blending-rules-in-json

**Pull request closed without merging**
